# Generated by Django 5.1.6 on 2025-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ca', models.IntegerField(max_length=100)),
                ('tamanho', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(max_length=100)),
                ('uni_medida', models.IntegerField(max_length=100)),
            ],
        ),
    ]
