# Generated by Django 5.1.6 on 2025-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_alter_epi_ca_alter_epi_tamanho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
