# Generated by Django 5.1.6 on 2025-02-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('centro_custo', models.IntegerField(max_length=30)),
            ],
        ),
    ]
