# Generated by Django 5.1.6 on 2025-02-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='name',
        ),
    ]
