# Generated by Django 5.1.6 on 2025-02-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_rename_nome_produto_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='name',
        ),
    ]
