# Generated by Django 5.1.6 on 2025-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_rename_nome_usuario_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='ca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epi',
            name='tamanho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='uni_medida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='centro_custo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
