# Generated by Django 5.1.6 on 2025-02-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_rename_uni_medida_produto_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='ca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='epi',
            name='tamanho',
            field=models.CharField(max_length=100),
        ),
    ]
